In [22]:
import pandas as pd
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [23]:
data = pd.read_csv("Cleaned_Dataset.csv")
data.head()

,Student_ID,Student_Name,Study_Hours,Attendance_Percentage,Internal_Assessment_Score,Previous_Academic_Result,Final_Grade,Gender,Age,Sleep_Hours
0,STU001,Krishna Iyer,6.7,74.9,41.4,83.8,B,Male,21.0,8.2
1,STU002,Ayushi Bansal,9.6,73.3,41.9,76.4,D,Female,20.0,8.7
2,STU003,Vivaan Gupta,7.6,67.0,40.1,60.8,C,Male,21.0,7.0
3,STU004,Manav Mehta,6.4,84.3,49.5,79.8,B,Male,21.0,7.0
4,STU005,Nikhil Nair,2.4,80.7,33.4,76.4,C,Male,23.0,8.2

In [24]:
data.drop(columns=['Student_ID','Student_Name'], axis=1, inplace=True)

data.head()

,Study_Hours,Attendance_Percentage,Internal_Assessment_Score,Previous_Academic_Result,Final_Grade,Gender,Age,Sleep_Hours
0,6.7,74.9,41.4,83.8,B,Male,21.0,8.2
1,9.6,73.3,41.9,76.4,D,Female,20.0,8.7
2,7.6,67.0,40.1,60.8,C,Male,21.0,7.0
3,6.4,84.3,49.5,79.8,B,Male,21.0,7.0
4,2.4,80.7,33.4,76.4,C,Male,23.0,8.2

In [25]:
data['Gender'] = data['Gender'].map({
    'Male': 0,'Female': 1
})
data.head()

,Study_Hours,Attendance_Percentage,Internal_Assessment_Score,Previous_Academic_Result,Final_Grade,Gender,Age,Sleep_Hours
0,6.7,74.9,41.4,83.8,B,0,21.0,8.2
1,9.6,73.3,41.9,76.4,D,1,20.0,8.7
2,7.6,67.0,40.1,60.8,C,0,21.0,7.0
3,6.4,84.3,49.5,79.8,B,0,21.0,7.0
4,2.4,80.7,33.4,76.4,C,0,23.0,8.2

In [26]:
X = data.drop('Final_Grade', axis=1)
y = data['Final_Grade']

scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

print(X_scaled[:5])

[[0.63333333 0.3725     0.53866667 0.73       0.         0.5
  0.05086521]
 [0.95555556 0.3325     0.552      0.60666667 1.         0.375
  0.05692059]
 [0.73333333 0.175      0.504      0.34666667 0.         0.5
  0.03633229]
 [0.6        0.6075     0.75466667 0.66333333 0.         0.5
  0.03633229]
 [0.15555556 0.5175     0.32533333 0.60666667 0.         0.75
  0.05086521]]

In [27]:
X = data.drop('Final_Grade', axis=1)
y = data['Final_Grade']

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
print(X_scaled[:5])

[[ 4.38155570e-01 -5.14075759e-01 -1.32784267e-03  6.57081958e-01
  -1.16984859e+00  7.05872875e-03 -4.67363608e-02]
 [ 1.64666516e+00 -6.66530865e-01  6.51973412e-02  2.15391932e-01
   8.54811479e-01 -4.57331321e-01  2.86686962e-03]
 [ 8.13210270e-01 -1.26682284e+00 -1.74293321e-01 -7.15738393e-01
  -1.16984859e+00  7.05872875e-03 -1.65784114e-01]
 [ 3.13137336e-01  3.81597989e-01  1.07638014e+00  4.18330592e-01
  -1.16984859e+00  7.05872875e-03 -1.65784114e-01]
 [-1.35377244e+00  3.85740004e-02 -1.06573078e+00  2.15391932e-01
  -1.16984859e+00  9.35838828e-01 -4.67363608e-02]]

In [29]:
# Numeric (for regression)
data['Final_Grade_Numeric'] = data['Final_Grade'].map({
    'A': 90, 'B': 75, 'C': 60, 'D': 40, 'E': 30, 'F': 20
})

# Binary classification
data['Result'] = data['Final_Grade'].map({
    'A': 1, 'B': 1, 'C': 1,
    'D': 0, 'E': 0, 'F': 0
})

# Label for display
data['Result_Label'] = data['Result'].map({1: 'Pass', 0: 'Fail'})

# Multi-class label
data['Grade_Label'] = data['Final_Grade_Numeric'].apply(
    lambda x: 'A' if x >= 90 else
              'B' if x >= 75 else
              'C' if x >= 60 else
              'D' if x >= 40 else
              'F'
)

In [41]:
data.head(5)

,Study_Hours,Attendance_Percentage,Internal_Assessment_Score,Previous_Academic_Result,Final_Grade,Gender,Age,Sleep_Hours,Final_Grade_Numeric,Result,Result_Label,Grade_Label
0,6.7,74.9,41.4,83.8,B,0,21.0,8.2,75,1,Pass,B
1,9.6,73.3,41.9,76.4,D,1,20.0,8.7,40,0,Fail,D
2,7.6,67.0,40.1,60.8,C,0,21.0,7.0,60,1,Pass,C
3,6.4,84.3,49.5,79.8,B,0,21.0,7.0,75,1,Pass,B
4,2.4,80.7,33.4,76.4,C,0,23.0,8.2,60,1,Pass,C

In [30]:
X = data.drop(['Final_Grade', 'Result_Label', 'Grade_Label'], axis=1)
y = data['Final_Grade_Numeric']

In [31]:
model = LinearRegression()
fs_forward = SequentialFeatureSelector(model,n_features_to_select=3,direction='forward')

In [32]:
fs_forward.fit(X, y)

SequentialFeatureSelector(estimator=LinearRegression(), n_features_to_select=3)

In [33]:
forward_features = X.columns[fs_forward.get_support()]
print("Forward Selected Features:")
print(list(forward_features))

Forward Selected Features:
['Study_Hours', 'Attendance_Percentage', 'Final_Grade_Numeric']

In [34]:
model = LinearRegression()
fs_backward = SequentialFeatureSelector(model,n_features_to_select=3,direction='backward')

In [35]:
fs_backward.fit(X, y)

SequentialFeatureSelector(direction='backward', estimator=LinearRegression(),
                          n_features_to_select=3)

In [36]:
backward_features = X.columns[fs_backward.get_support()]
print("Backward Selected Features:")
print(list(backward_features))

Backward Selected Features:
['Sleep_Hours', 'Final_Grade_Numeric', 'Result']

In [37]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

pca = PCA(n_components=3)   # you can change this number
X_pca = pca.fit_transform(X_scaled)

import pandas as pd
X_pca_df = pd.DataFrame(X_pca, columns=['PC1', 'PC2', 'PC3'])

print("PCA Components:")
print(X_pca_df.head())

PCA Components:
        PC1       PC2       PC3
0  0.943735 -0.135383 -0.809341
1 -1.303276  1.844490  0.449079
2 -0.231309  0.348658 -0.745251
3  1.267809  0.480335 -0.999230
4 -0.356631 -1.750857 -0.324145